### ISSUE TITLE
Neues Berechnungsmodell

### ISSUE THREAD

**Issue by codedust** [AStA-TU-Darmstadt/studi-mat#3]
Anpassung des Berechnungsmodells entsprechend des Modells des Wahl-O-Mat der bpb.

http://www.bpb.de/system/files/dokument_pdf/Rechenmodell%20des%20Wahl-O-Mat.pdf

**Comment by openpaul** [comment]
Gute Idee, sollte schnell machbar sein.

**Comment by codedust** [comment]
Ja, ich habe vor, den Wahl-o-Mat bis zum 17.5. (Beschluss über die eingerichten Wahlvorschläge) auf Vordermann zu bringen.

**Comment by codedust** [comment]
Ja, ich habe vor, den Wahl-o-Mat bis zum 17.5. (Beschluss über die eingerichten Wahlvorschläge) ein wenig auf Vordermann zu bringen.
